### ISSUE TITLE
Desenvolver Esfera

### ISSUE THREAD

**Issue by josutk** [josutk/PinBall-3D#4]
- [x] Deve ser implementada assim como a esfera do Pinball Original;
- [x] Deve ter a aparência metálica;
- [x] Deve dar a impressão de estar girando ao movimentar-se pela fase;
- [x] Deve dar a impressão de ter o peso da esfera de Pinball Original:
  - [x] Sendo pouco suscetível a saltos;
  - [x] Tendo força e velocidade relevantes para a fase e interação com outros componentes;

**Comment by AllanNobre** [comment]
@igor-gme , verifica os critérios, por favor!
