### ISSUE TITLE
Desenvolver Drop-Target

### ISSUE THREAD

**Issue by josutk** [josutk/PinBall-3D#6]
- [x] Implementa Drop-target assim como é no Pinball Analógico;
- [x] Podem ser criados de forma individual ou em grupo;
- [x] Devem abaixar quando acertados;
- [x] Devem levantar quando o conjunto de Drop-targets atrelados estiverem todos abaixados;
- [x] Deve aparecer um pedaço do Drop-target que está abaixado;

**Comment by AllanNobre** [comment]
@Rdlenke , verifica os critérios de aceitação, por favor!
